# Copyright 2023 Morse Micro
# SPDX-License-Identifier: GPL-2.0-or-later OR LicenseRef-MorseMicroCommercial

import os

env = Environment(tools=['default', 'style', 'log'],
                    ENV=os.environ.copy(),
                    CC=os.environ.get('CC', 'gcc'), LD=os.environ.get('LD', 'ld'))

# Set custom prefix and suffix
env.Replace(SHLIBPREFIX='', SHLIBSUFFIX='.mmext')

def get_git_desc():
    ver = ARGUMENTS.get('MORSE_VERSION', 0)
    if type(ver) is int:
        return "Undefined"
    return ver


env.Append(
    CFLAGS=["-fPIC", "-O2", "-Wall", "-Werror", '-DMORSE_VERSION=\\"' + get_git_desc() + '\\"']
)
env.Append(LINKFLAGS=["-rdynamic", "-fPIC", "-Wl,--export-dynamic"])

Export('env')

incs = ['.', 'include']
env.Append(CPPPATH=list(map(lambda x: Dir(x).srcnode(), incs)))

env.Append(LIBS=['pthread', 'libconfig', 'dl'])

backend = env.SConscript('backend/SConscript')
engine = RecursiveGlob('engine/', '*.c')
misc = RecursiveGlob('misc/', '*.c')

style = env.Style('style.txt', engine + backend['style'])

env.Alias('lint', style)

core = env.Object([
    engine, misc
]) + backend['objs']

# Names of loadable modules. Assumes they each have a SConscript in their directories
module_names = ['dcs']

items = []
# Execute SConscript file for each module
for module in module_names:
    module_src = str(Dir(f"modules/{module}").srcnode())
    sconscript_file = os.path.join(module_src, "SConscript")
    if not os.path.isfile(sconscript_file):
        print(f"WARNING: Could not find SConscript for module {module} and path {sconscript_file}")
        continue
    items += env.SConscript(sconscript_file, variant_dir=f'modules/{module}', duplicate=0)

apps = [
    env.Program('smart_manager', [
        core,
        'smart_manager_main.c'
    ]),
] + items

Alias('apps', apps)

if not env.GetOption('clean'):
    Default(apps)
